[build]
  base = "/"
  command = "npm run build"
  publish = "apps/studio/dist"

[functions]
  directory = "apps/functions/src"
  node_bundler = "esbuild"

[dev]
  command = "npm -w apps/studio run dev"
  functions = "apps/functions/src"
  port = 8888

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
