[build]
  base = "/"
  command = "npm run build"
  publish = "apps/site/dist"

[functions]
  directory = "apps/_shared_functions/src"
  node_bundler = "esbuild"

[dev]
  command = "npm --workspace studio run dev"
  functions = "apps/_shared_functions/src"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
