export { RUNTIME_TEMPLATE_FILES } from "./default_template/runtime-files";
export {
  FONTS_TEMPLATE,
  FOOTER_CONTENT_TEMPLATE,
  GLOBAL_STYLES_TEMPLATE,
  HEADER_CONTENT_TEMPLATE,
  HOME_PAGE_TEMPLATE,
  SEO_CONTENT_TEMPLATE,
  SOLIDARY_CONTENT_TEMPLATE,
  STRUCTURE_TEMPLATE,
  TEMPLATE_SOLIDARY,
  TEMPLATE_SOLIDARY_LINKS,
  TOKENS_TEMPLATE
} from "./default_template/scaffold";

export const ACTIVE_SITE_TEMPLATE_ID = "default_template";
