alter table public.github_app_user_tokens
  add column if not exists access_token_encrypted text,
  add column if not exists refresh_token_encrypted text,
  add column if not exists token_encryption_key_version text not null default 'v1';

alter table public.github_app_user_tokens
  alter column access_token drop not null;

-- Remove previously stored plaintext values. Users reconnect once under encrypted storage.
update public.github_app_user_tokens
set
  access_token = null,
  refresh_token = null
where access_token is not null
   or refresh_token is not null;

create table if not exists public.github_repo_action_audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete set null,
  function_name text not null,
  action text not null,
  owner text,
  repo text,
  repo_full_name text,
  decision text not null check (decision in ('allowed', 'denied', 'error')),
  token_source text,
  http_status integer,
  message text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists github_repo_action_audit_logs_user_created_idx
  on public.github_repo_action_audit_logs (user_id, created_at desc);

create index if not exists github_repo_action_audit_logs_repo_created_idx
  on public.github_repo_action_audit_logs (repo_full_name, created_at desc);

create index if not exists github_repo_action_audit_logs_function_created_idx
  on public.github_repo_action_audit_logs (function_name, created_at desc);

alter table public.github_repo_action_audit_logs enable row level security;
